# Add this layer to BBPATH
BBPATH .= ":${LAYERDIR}"

# Include all recipes and append files
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Define collection name (must be unique)
BBFILE_COLLECTIONS += "rdkwirelessconnectivity"

# Match all files under this layer
BBFILE_PATTERN_rdkwirelessconnectivity = "^${LAYERDIR}/"

# Priority (higher wins in conflicts)
BBFILE_PRIORITY_rdkwirelessconnectivity = "6"

# Dependencies
LAYERDEPENDS_rdkwirelessconnectivity = "core"

# Compatible Yocto releases
LAYERSERIES_COMPAT_rdkwirelessconnectivity = "dunfell kirkstone"
